"""initial schema

Revision ID: 6e73234c7695
Revises: 0001
Create Date: 2026-04-27 13:37:58.875131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '6e73234c7695'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=512), nullable=False),
    sa.Column('action', sa.Enum('read', 'write', 'delete', 'approve', 'reject', 'export', 'permission_denied', name='audit_action_enum'), nullable=False),
    sa.Column('target_type', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.String(length=512), nullable=True),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dt_channel_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=512), nullable=False),
    sa.Column('channel_type', sa.Enum('slack', 'discord', 'whatsapp', 'api', name='channel_type_enum'), nullable=False),
    sa.Column('permission_level', sa.Enum('read_only_chat', 'learn_candidate', 'admin', name='permission_level_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_user_ids', sa.ARRAY(sa.String(length=512)), nullable=True),
    sa.Column('channel_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_channel_configs_channel_id'), 'dt_channel_configs', ['channel_id'], unique=True)
    op.create_table('dt_conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=256), nullable=False),
    sa.Column('channel_type', sa.String(length=64), nullable=False),
    sa.Column('channel_message_id', sa.String(length=512), nullable=True),
    sa.Column('sender_id', sa.String(length=256), nullable=False),
    sa.Column('sender_name', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction_enum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_conversation_messages_channel_id'), 'dt_conversation_messages', ['channel_id'], unique=False)
    op.create_table('dt_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.Enum('person', 'place', 'organization', 'concept', 'other', name='entity_type_enum'), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=512)), nullable=True),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_entities_name'), 'dt_entities', ['name'], unique=False)
    op.create_table('dt_memory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.String(length=256), nullable=False),
    sa.Column('memory_type', sa.Enum('biographical', 'personality', 'idea', 'event', 'preference', 'skill', 'relationship', 'conversation', name='memory_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('source_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', 'exported', name='memory_status_enum'), nullable=False),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_memory_items_subject_id'), 'dt_memory_items', ['subject_id'], unique=False)
    op.create_table('dt_raw_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('article', 'document', 'transcript', 'conversation', 'other', name='source_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dt_memory_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_source_id', sa.UUID(), nullable=True),
    sa.Column('proposed_content', sa.Text(), nullable=False),
    sa.Column('proposed_type', sa.String(length=64), nullable=False),
    sa.Column('proposed_confidence', sa.Float(), nullable=False),
    sa.Column('proposed_tags', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='candidate_status_enum'), nullable=False),
    sa.Column('reviewer_id', sa.String(length=256), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('candidate_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_source_id'], ['dt_raw_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_memory_candidates_raw_source_id'), 'dt_memory_candidates', ['raw_source_id'], unique=False)
    op.create_table('dt_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['dt_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['dt_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dt_relationships_from_entity_id'), 'dt_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_dt_relationships_to_entity_id'), 'dt_relationships', ['to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dt_relationships_to_entity_id'), table_name='dt_relationships')
    op.drop_index(op.f('ix_dt_relationships_from_entity_id'), table_name='dt_relationships')
    op.drop_table('dt_relationships')
    op.drop_index(op.f('ix_dt_memory_candidates_raw_source_id'), table_name='dt_memory_candidates')
    op.drop_table('dt_memory_candidates')
    op.drop_table('dt_raw_sources')
    op.drop_index(op.f('ix_dt_memory_items_subject_id'), table_name='dt_memory_items')
    op.drop_table('dt_memory_items')
    op.drop_index(op.f('ix_dt_entities_name'), table_name='dt_entities')
    op.drop_table('dt_entities')
    op.drop_index(op.f('ix_dt_conversation_messages_channel_id'), table_name='dt_conversation_messages')
    op.drop_table('dt_conversation_messages')
    op.drop_index(op.f('ix_dt_channel_configs_channel_id'), table_name='dt_channel_configs')
    op.drop_table('dt_channel_configs')
    op.drop_table('dt_audit_logs')
    # ### end Alembic commands ###
